package collections;

import java.util.HashMap;
import java.util.Map;

public class StudentSemisterMarks {

	public static void main(String[] args) {
		/*Map<String, Integer> studentMarks = new HashMap<>();
		studentMarks.put("Dhanalakshmi", 1900);
		studentMarks.put("Naresh", 3000);
		studentMarks.put("Vasavi", 3100);
		studentMarks.put("Pavan", 3500);
		studentMarks.put("Veerababu", 3700);
		System.out.println(studentMarks);
		System.out.println(studentMarks.get("Dhanalakshmi"));
		System.out.println(studentMarks.get("Naresh"));*/
		
		/*Map<String, Map<String, Integer>> studentMarks = new HashMap<>();
		Map<String, Integer> DhanalakshmiMarks = new HashMap<>();
		DhanalakshmiMarks.put("Semister1", 700);
		DhanalakshmiMarks.put("Semister2", 400);
		DhanalakshmiMarks.put("Semister3", 500);
		DhanalakshmiMarks.put("Semister4", 300);
		DhanalakshmiMarks.put("Semister5", 900);
		DhanalakshmiMarks.put("Semister6", 350);
		DhanalakshmiMarks.put("Semister7", 750);
		studentMarks.put("Dhanalakshmi", DhanalakshmiMarks);
		
		Map<String, Integer> NareshMarks = new HashMap<>();
		NareshMarks.put("Semister1", 800);
		NareshMarks.put("Semister2", 900);
		NareshMarks.put("Semister3", 500);
		NareshMarks.put("Semister4", 600);
		NareshMarks.put("Semister5", 400);
		NareshMarks.put("Semister6", 650);
		NareshMarks.put("Semister7", 850);
		NareshMarks.put("Semister8", 550);
		studentMarks.put("Naresh", NareshMarks);
		
		Map<String, Integer> VasaviMarks = new HashMap<>();
		VasaviMarks.put("Semister1", 700);
		VasaviMarks.put("Semister2", 800);
		VasaviMarks.put("Semister3", 400);
		VasaviMarks.put("Semister4", 600);
		VasaviMarks.put("Semister5", 900);
		VasaviMarks.put("Semister6", 750);
		VasaviMarks.put("Semister7", 350);
		VasaviMarks.put("Semister8", 650);
		studentMarks.put("Vasavi", VasaviMarks);
		
		Map<String, Integer> PavanMarks = new HashMap<>();
		PavanMarks.put("Semister1", 600);
		PavanMarks.put("Semister2", 700);
		PavanMarks.put("Semister3", 400);
		PavanMarks.put("Semister4", 500);
		PavanMarks.put("Semister5", 900);
		PavanMarks.put("Semister6", 850);
		PavanMarks.put("Semister7", 450);
		PavanMarks.put("Semister8", 750);
		studentMarks.put("Pavan", PavanMarks);
		
		Map<String, Integer> VeerababuMarks = new HashMap<>();
		VeerababuMarks.put("Semister1", 500);
		VeerababuMarks.put("Semister2", 700);
		VeerababuMarks.put("Semister3", 800);
		VeerababuMarks.put("Semister4", 300);
		VeerababuMarks.put("Semister5", 950);
		VeerababuMarks.put("Semister6", 650);
		VeerababuMarks.put("Semister7", 750);
		VeerababuMarks.put("Semister8", 550);
		studentMarks.put("Veerababu", VeerababuMarks);
		System.out.println(studentMarks);*/
		
		Map<String, Map<String, Map<String, Integer>>> studentMarks = new HashMap<>();
	    Map<String, Map<String, Integer>> DhanalakshmiSemister = new HashMap<>();
	    Map<String, Integer> DhanalakshmiSemister1SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister1SubjectMarks.put("English", 80);
	    DhanalakshmiSemister1SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister1SubjectMarks.put("BOM", 95);
	    DhanalakshmiSemister1SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister1SubjectMarks.put("AUDITING", 95);
	    Map<String, Integer> DhanalakshmiSemister2SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister2SubjectMarks.put("English", 80);
	    DhanalakshmiSemister2SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister2SubjectMarks.put("BOM", 95);
	    DhanalakshmiSemister2SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister2SubjectMarks.put("AUDITING", 95);
	    Map<String, Integer> DhanalakshmiSemister3SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister3SubjectMarks.put("English", 90);
	    DhanalakshmiSemister3SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister3SubjectMarks.put("BOM", 95);
	    DhanalakshmiSemister3SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister3SubjectMarks.put("AUDITING", 95);
	    Map<String, Integer> DhanalakshmiSemister4SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister4SubjectMarks.put("English", 80);
	    DhanalakshmiSemister4SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister4SubjectMarks.put("BOM", 65);
	    DhanalakshmiSemister4SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister4SubjectMarks.put("AUDITING", 95);
	    Map<String, Integer> DhanalakshmiSemister5SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister5SubjectMarks.put("English", 80);
	    DhanalakshmiSemister5SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister5SubjectMarks.put("BOM", 95);
	    DhanalakshmiSemister5SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister5SubjectMarks.put("AUDITING", 95);
	    Map<String, Integer> DhanalakshmiSemister6SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister6SubjectMarks.put("English", 80);
	    DhanalakshmiSemister6SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister6SubjectMarks.put("BOM", 95);
	    DhanalakshmiSemister6SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister6SubjectMarks.put("AUDITING", 85);
	    Map<String, Integer> DhanalakshmiSemister7SubjectMarks = new HashMap<>();
	    DhanalakshmiSemister7SubjectMarks.put("English", 80);
	    DhanalakshmiSemister7SubjectMarks.put("Accountig", 90);
	    DhanalakshmiSemister7SubjectMarks.put("BOM", 85);
	    DhanalakshmiSemister7SubjectMarks.put("Business Statistics", 60);
	    DhanalakshmiSemister7SubjectMarks.put("AUDITING", 95);
	    DhanalakshmiSemister.put("Semister1", DhanalakshmiSemister1SubjectMarks);
	    DhanalakshmiSemister.put("Semister2", DhanalakshmiSemister2SubjectMarks);
	    DhanalakshmiSemister.put("Semister3", DhanalakshmiSemister3SubjectMarks);
	    DhanalakshmiSemister.put("Semister4", DhanalakshmiSemister4SubjectMarks);
	    DhanalakshmiSemister.put("Semister5", DhanalakshmiSemister5SubjectMarks);
	    DhanalakshmiSemister.put("Semister6", DhanalakshmiSemister6SubjectMarks);
	    DhanalakshmiSemister.put("Semister7", DhanalakshmiSemister7SubjectMarks);
	    
	    studentMarks.put("Dhanalakshmi", DhanalakshmiSemister);
	    System.out.println(studentMarks);
	    
		Map<String, Map<String, Map<String, Integer>>> studentMarks1 = new HashMap<>();
		Map<String, Map<String, Integer>> NareshSemister = new HashMap<>();
		Map<String, Integer> NareshSemister1SubjectMarks = new HashMap<>();
		NareshSemister1SubjectMarks.put("English", 75);
		NareshSemister1SubjectMarks.put("Physics", 68);
		NareshSemister1SubjectMarks.put("Chemistry", 85);
		NareshSemister1SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister2SubjectMarks = new HashMap<>();
		NareshSemister2SubjectMarks.put("English", 75);
		NareshSemister2SubjectMarks.put("Physics", 68);
		NareshSemister2SubjectMarks.put("Chemistry", 85);
		NareshSemister2SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister3SubjectMarks = new HashMap<>();
		NareshSemister3SubjectMarks.put("English", 75);
		NareshSemister3SubjectMarks.put("Physics", 68);
		NareshSemister3SubjectMarks.put("Chemistry", 85);
		NareshSemister3SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister4SubjectMarks = new HashMap<>();
		NareshSemister4SubjectMarks.put("English", 75);
		NareshSemister4SubjectMarks.put("Physics", 68);
		NareshSemister4SubjectMarks.put("Chemistry", 85);
		NareshSemister4SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister5SubjectMarks = new HashMap<>();
		NareshSemister5SubjectMarks.put("English", 75);
		NareshSemister5SubjectMarks.put("Physics", 68);
		NareshSemister5SubjectMarks.put("Chemistry", 85);
		NareshSemister5SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister6SubjectMarks = new HashMap<>();
		NareshSemister6SubjectMarks.put("English", 75);
		NareshSemister6SubjectMarks.put("Physics", 68);
		NareshSemister6SubjectMarks.put("Chemistry", 85);
		NareshSemister6SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister7SubjectMarks = new HashMap<>();
		NareshSemister7SubjectMarks.put("English", 75);
		NareshSemister7SubjectMarks.put("Physics", 68);
		NareshSemister7SubjectMarks.put("Chemistry", 85);
		NareshSemister7SubjectMarks.put("Drawing", 70);
		Map<String, Integer> NareshSemister8SubjectMarks = new HashMap<>();
		NareshSemister8SubjectMarks.put("English", 75);
		NareshSemister8SubjectMarks.put("Physics", 68);
		NareshSemister8SubjectMarks.put("Chemistry", 85);
		NareshSemister8SubjectMarks.put("Drawing", 70);
		NareshSemister.put("Semister1", NareshSemister1SubjectMarks);
		NareshSemister.put("Semister2", NareshSemister2SubjectMarks);
		NareshSemister.put("Semister3", NareshSemister3SubjectMarks);
		NareshSemister.put("Semister4", NareshSemister4SubjectMarks);
		NareshSemister.put("Semister5", NareshSemister5SubjectMarks);
		NareshSemister.put("Semister6", NareshSemister6SubjectMarks);
		NareshSemister.put("Semister7", NareshSemister7SubjectMarks);
		NareshSemister.put("Semister8", NareshSemister8SubjectMarks);
		
		studentMarks1.put("Naresh", NareshSemister);
		System.out.println(studentMarks1);
		
		Map<String, Map<String, Map<String, Integer>>> studentMarks2 = new HashMap<>();
		Map<String, Map<String, Integer>> VasaviSemister = new HashMap<>();
		Map<String, Integer> VasaviSemister1SubjectMarks = new HashMap<>();
		VasaviSemister1SubjectMarks.put("English", 95);
		VasaviSemister1SubjectMarks.put("Physics", 78);
		VasaviSemister1SubjectMarks.put("Chemistry", 65);
		VasaviSemister1SubjectMarks.put("Drawing", 50);
		Map<String, Integer> VasaviSemister2SubjectMarks = new HashMap<>();
		VasaviSemister2SubjectMarks.put("English", 65);
		VasaviSemister2SubjectMarks.put("Physics", 58);
		VasaviSemister2SubjectMarks.put("Chemistry", 65);
		VasaviSemister2SubjectMarks.put("Drawing", 60);
		Map<String, Integer> VasaviSemister3SubjectMarks = new HashMap<>();
		VasaviSemister3SubjectMarks.put("English", 95);
		VasaviSemister3SubjectMarks.put("Physics", 88);
		VasaviSemister3SubjectMarks.put("Chemistry", 45);
		VasaviSemister3SubjectMarks.put("Drawing", 70);
		Map<String, Integer> VasaviSemister4SubjectMarks = new HashMap<>();
		VasaviSemister4SubjectMarks.put("English", 85);
		VasaviSemister4SubjectMarks.put("Physics", 98);
		VasaviSemister4SubjectMarks.put("Chemistry", 75);
		VasaviSemister4SubjectMarks.put("Drawing", 50);
		Map<String, Integer> VasaviSemister5SubjectMarks = new HashMap<>();
		VasaviSemister5SubjectMarks.put("English", 85);
		VasaviSemister5SubjectMarks.put("Physics", 98);
		VasaviSemister5SubjectMarks.put("Chemistry", 85);
		VasaviSemister5SubjectMarks.put("Drawing", 60);
		Map<String, Integer> VasaviSemister6SubjectMarks = new HashMap<>();
		VasaviSemister6SubjectMarks.put("English", 65);
		VasaviSemister6SubjectMarks.put("Physics", 58);
		VasaviSemister6SubjectMarks.put("Chemistry", 85);
		VasaviSemister6SubjectMarks.put("Drawing", 50);
		Map<String, Integer> VasaviSemister7SubjectMarks = new HashMap<>();
		VasaviSemister7SubjectMarks.put("English", 85);
		VasaviSemister7SubjectMarks.put("Physics", 88);
		VasaviSemister7SubjectMarks.put("Chemistry", 95);
		VasaviSemister7SubjectMarks.put("Drawing", 80);
		Map<String, Integer> VasaviSemister8SubjectMarks = new HashMap<>();
		VasaviSemister8SubjectMarks.put("English", 65);
		VasaviSemister8SubjectMarks.put("Physics", 88);
		VasaviSemister8SubjectMarks.put("Chemistry", 95);
		VasaviSemister8SubjectMarks.put("Drawing", 80);
		VasaviSemister.put("Semister1", VasaviSemister1SubjectMarks);
		VasaviSemister.put("Semister2", VasaviSemister2SubjectMarks);
		VasaviSemister.put("Semister3", VasaviSemister3SubjectMarks);
		VasaviSemister.put("Semister4", VasaviSemister4SubjectMarks);
		VasaviSemister.put("Semister5", VasaviSemister5SubjectMarks);
		VasaviSemister.put("Semister6", VasaviSemister6SubjectMarks);
		VasaviSemister.put("Semister7", VasaviSemister7SubjectMarks);
		VasaviSemister.put("Semister8", VasaviSemister8SubjectMarks);
		
		studentMarks2.put("Vasavi", VasaviSemister);
		System.out.println(studentMarks2);
	   
	}

}
